export const UPDATER_TYPE = 'UPDATER_TYPE';
export const UPDATER_SETTER = 'UPDATER_SETTER';
export const UPDATER_USER_DEFINE = 'UPDATER_USER_DEFINE';
export const CONVERT_TO_OBSERVABLE = 'CONVERT_TO_OBSERVABLE';
